### PR TITLE
Feature ldaps

### PR DESCRIPTION
**Pull request by houldsg**
Tested and working on our AD server (which requires a secure connection to authenticate)

### CODE REVIEW

**Comment by einfallstoll** [comment]
This is awesome! Gonna have to update a few spacing issues to satisfy my OCD though ;-)

**Comment by houldsg** [comment]
Cool! Will this make it into the npm package?
(I'd like to just include it from npm instead of our private gitlab server)

**Comment by einfallstoll** [comment]
... aaaaaaand it's live

**Comment by houldsg** [comment]
Perfect. Thanks!  :thumbsup:

**Pull request merged**
