### PR TITLE
Separated NTLM_Proxy client from express middleware module

### PR DESCRIPTION
**Pull request by mancioshell**
@einfallstoll i have created this push request in order to separate NTLM_Proxy client from express middleware. This refer to this open issue #41

### CODE REVIEW

**Comment by einfallstoll** [comment]
I just had a look at it and this is awesome! Nice work.

This isn't `express-ntlm` anymore, so I'd fork this in a separate module and update this module to depend on the `ntlm-ad-proxy` (or whatever we call it), right?

**Comment by mancioshell** [comment]
@einfallstoll Thank you so much, but i just refactored your awesome work :smiley: 
Yep, it should be a separate module. We could call ntlm-client or ntlm-ad-client or whatever you want! Tell me when you will have done, so i will be able to publish my hapi authentication strategy.

**Comment by einfallstoll** [comment]
I now separated the whole ntlm-client into [`ntlm-ad-client`](https://github.com/einfallstoll/ntlm-ad-client) this should close #41 and also references #31. I already published it to [npm](https://www.npmjs.com/package/ntlm-ad-client) because I didn't think of testing might have been a good idea (*yup, I'm reaaaaally smart*).

**Comment by mancioshell** [comment]
I have published ntlm hapi authentication strategy at [hapi-ntlm](https://github.com/mancioshell/hapi-ntlm).
This should close this #43 and this #41 
Thank you for quote me in [ntlm-ad-client](https://github.com/einfallstoll/ntlm-ad-client) :smile:

**Comment by einfallstoll** [comment]
Good work needs appreciation.

**Comment by einfallstoll** [comment]
I should add "🇮🇹 Software" to the README.

**Comment by mancioshell** [comment]
ahahahah Yes, somethings like Italians do it well! 😄

**Pull request closed without merging**
